services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      pull: true
    ports:
      - "8000:8000"
    environment:
      - LINE_COUNTER_STATE_PATH=/data/state.json
    volumes:
      - backend_state:/data
    devices:
      - "/dev/video0:/dev/video0"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_BACKEND_URL: http://localhost:8000
      pull: true
    ports:
      - "5423:5423"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_state:
